<?php

/**
 * BaseGenero
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $abreviacion
 * @property Doctrine_Collection $Estudiantes
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getAbreviacion() Returns the current record's "abreviacion" value
 * @method Doctrine_Collection getEstudiantes() Returns the current record's "Estudiantes" collection
 * @method Genero              setId()          Sets the current record's "id" value
 * @method Genero              setNombre()      Sets the current record's "nombre" value
 * @method Genero              setAbreviacion() Sets the current record's "abreviacion" value
 * @method Genero              setEstudiantes() Sets the current record's "Estudiantes" collection
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGenero extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('genero');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('abreviacion', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));

        $this->option('charset', 'latin1');
        $this->option('collate', 'latin1_spanish_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estudiante as Estudiantes', array(
             'local' => 'id',
             'foreign' => 'Genero_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}