<?php

/**
 * BaseAsistencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $fecha
 * @property boolean $asistio
 * @property integer $Estudiante_id
 * @property integer $CursoProgramado_id
 * @property integer $CursoProgramado_Curso_id
 * @property integer $CursoProgramado_Institucion_id
 * @property Estudiante $Estudiante
 * @property CursoProgramado $CursoProgramadoCurso
 * 
 * @method timestamp       getFecha()                          Returns the current record's "fecha" value
 * @method boolean         getAsistio()                        Returns the current record's "asistio" value
 * @method integer         getEstudianteId()                   Returns the current record's "Estudiante_id" value
 * @method integer         getCursoProgramadoId()              Returns the current record's "CursoProgramado_id" value
 * @method integer         getCursoProgramadoCursoId()         Returns the current record's "CursoProgramado_Curso_id" value
 * @method integer         getCursoProgramadoInstitucionId()   Returns the current record's "CursoProgramado_Institucion_id" value
 * @method Estudiante      getEstudiante()                     Returns the current record's "Estudiante" value
 * @method CursoProgramado getCursoProgramadoCurso()           Returns the current record's "CursoProgramadoCurso" value
 * @method Asistencia      setFecha()                          Sets the current record's "fecha" value
 * @method Asistencia      setAsistio()                        Sets the current record's "asistio" value
 * @method Asistencia      setEstudianteId()                   Sets the current record's "Estudiante_id" value
 * @method Asistencia      setCursoProgramadoId()              Sets the current record's "CursoProgramado_id" value
 * @method Asistencia      setCursoProgramadoCursoId()         Sets the current record's "CursoProgramado_Curso_id" value
 * @method Asistencia      setCursoProgramadoInstitucionId()   Sets the current record's "CursoProgramado_Institucion_id" value
 * @method Asistencia      setEstudiante()                     Sets the current record's "Estudiante" value
 * @method Asistencia      setCursoProgramadoCurso()           Sets the current record's "CursoProgramadoCurso" value
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsistencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia');
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             'primary' => true,
             ));
        $this->hasColumn('asistio', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('Estudiante_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('CursoProgramado_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('CursoProgramado_Curso_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('CursoProgramado_Institucion_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_Asistencia_Estudiante1', array(
             'fields' => 
             array(
              0 => 'Estudiante_id',
             ),
             ));
        $this->index('fk_Asistencia_CursoProgramado1', array(
             'fields' => 
             array(
              0 => 'CursoProgramado_id',
              1 => 'CursoProgramado_Curso_id',
              2 => 'CursoProgramado_Institucion_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'Estudiante_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('CursoProgramado as CursoProgramadoCurso', array(
             'local' => 'CursoProgramado_Curso_id',
             'foreign' => 'Curso_id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}