<?php

/**
 * BaseServicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property decimal $valor
 * @property Doctrine_Collection $Cursos
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method decimal             getValor()       Returns the current record's "valor" value
 * @method Doctrine_Collection getCursos()      Returns the current record's "Cursos" collection
 * @method Servicio            setId()          Sets the current record's "id" value
 * @method Servicio            setNombre()      Sets the current record's "nombre" value
 * @method Servicio            setDescripcion() Sets the current record's "descripcion" value
 * @method Servicio            setValor()       Sets the current record's "valor" value
 * @method Servicio            setCursos()      Sets the current record's "Cursos" collection
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('valor', 'decimal', 7, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => 7,
             ));

        $this->option('charset', 'latin1');
        $this->option('collate', 'latin1_spanish_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Curso as Cursos', array(
             'local' => 'id',
             'foreign' => 'Servicio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}