<?php

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $apellidos
 * @property string $nombres
 * @property string $telefono
 * @property string $movil
 * @property string $email
 * @property string $username
 * @property string $password
 * @property integer $Perfil_id
 * @property Perfil $Perfil
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getApellidos() Returns the current record's "apellidos" value
 * @method string  getNombres()   Returns the current record's "nombres" value
 * @method string  getTelefono()  Returns the current record's "telefono" value
 * @method string  getMovil()     Returns the current record's "movil" value
 * @method string  getEmail()     Returns the current record's "email" value
 * @method string  getUsername()  Returns the current record's "username" value
 * @method string  getPassword()  Returns the current record's "password" value
 * @method integer getPerfilId()  Returns the current record's "Perfil_id" value
 * @method Perfil  getPerfil()    Returns the current record's "Perfil" value
 * @method Usuario setId()        Sets the current record's "id" value
 * @method Usuario setApellidos() Sets the current record's "apellidos" value
 * @method Usuario setNombres()   Sets the current record's "nombres" value
 * @method Usuario setTelefono()  Sets the current record's "telefono" value
 * @method Usuario setMovil()     Sets the current record's "movil" value
 * @method Usuario setEmail()     Sets the current record's "email" value
 * @method Usuario setUsername()  Sets the current record's "username" value
 * @method Usuario setPassword()  Sets the current record's "password" value
 * @method Usuario setPerfilId()  Sets the current record's "Perfil_id" value
 * @method Usuario setPerfil()    Sets the current record's "Perfil" value
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('apellidos', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('nombres', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('movil', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('username', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('password', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('Perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_Usuario_Perfil1', array(
             'fields' => 
             array(
              0 => 'Perfil_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Perfil', array(
             'local' => 'Perfil_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'apellidos',
              1 => 'nombres',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}