<?php

/**
 * BaseMunicipio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $codigo
 * @property string $nombre
 * @property Doctrine_Collection $Instituciones
 * @property Doctrine_Collection $Estudiantes
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getCodigo()        Returns the current record's "codigo" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method Doctrine_Collection getInstituciones() Returns the current record's "Instituciones" collection
 * @method Doctrine_Collection getEstudiantes()   Returns the current record's "Estudiantes" collection
 * @method Municipio           setId()            Sets the current record's "id" value
 * @method Municipio           setCodigo()        Sets the current record's "codigo" value
 * @method Municipio           setNombre()        Sets the current record's "nombre" value
 * @method Municipio           setInstituciones() Sets the current record's "Instituciones" collection
 * @method Municipio           setEstudiantes()   Sets the current record's "Estudiantes" collection
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMunicipio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('municipio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));

        $this->option('charset', 'latin1');
        $this->option('collate', 'latin1_spanish_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Institucion as Instituciones', array(
             'local' => 'id',
             'foreign' => 'Municipio_id'));

        $this->hasMany('Estudiante as Estudiantes', array(
             'local' => 'id',
             'foreign' => 'Municipio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}