<?php

/**
 * BaseMatricula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property integer $CursoProgramado_Curso_id
 * @property integer $CursoProgramado_Institucion_id
 * @property integer $CursoProgramado_PeriodoAcademico_id
 * @property integer $Estudiante_id
 * @property CursoProgramado $CursoProgramadoCurso
 * @property Estudiante $Estudiante
 * 
 * @method date            getFecha()                               Returns the current record's "fecha" value
 * @method integer         getCursoProgramadoCursoId()              Returns the current record's "CursoProgramado_Curso_id" value
 * @method integer         getCursoProgramadoInstitucionId()        Returns the current record's "CursoProgramado_Institucion_id" value
 * @method integer         getCursoProgramadoPeriodoAcademicoId()   Returns the current record's "CursoProgramado_PeriodoAcademico_id" value
 * @method integer         getEstudianteId()                        Returns the current record's "Estudiante_id" value
 * @method CursoProgramado getCursoProgramadoCurso()                Returns the current record's "CursoProgramadoCurso" value
 * @method Estudiante      getEstudiante()                          Returns the current record's "Estudiante" value
 * @method Matricula       setFecha()                               Sets the current record's "fecha" value
 * @method Matricula       setCursoProgramadoCursoId()              Sets the current record's "CursoProgramado_Curso_id" value
 * @method Matricula       setCursoProgramadoInstitucionId()        Sets the current record's "CursoProgramado_Institucion_id" value
 * @method Matricula       setCursoProgramadoPeriodoAcademicoId()   Sets the current record's "CursoProgramado_PeriodoAcademico_id" value
 * @method Matricula       setEstudianteId()                        Sets the current record's "Estudiante_id" value
 * @method Matricula       setCursoProgramadoCurso()                Sets the current record's "CursoProgramadoCurso" value
 * @method Matricula       setEstudiante()                          Sets the current record's "Estudiante" value
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMatricula extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('matricula');
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('CursoProgramado_Curso_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('CursoProgramado_Institucion_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('CursoProgramado_PeriodoAcademico_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('Estudiante_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_Matricula_CursoProgramado1', array(
             'fields' => 
             array(
              0 => 'CursoProgramado_Curso_id',
              1 => 'CursoProgramado_Institucion_id',
              2 => 'CursoProgramado_PeriodoAcademico_id',
             ),
             ));
        $this->index('fk_Matricula_Estudiante1', array(
             'fields' => 
             array(
              0 => 'Estudiante_id',
             ),
             ));
        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CursoProgramado as CursoProgramadoCurso', array(
             'local' => 'CursoProgramado_Curso_id',
             'foreign' => 'Curso_id'));

        $this->hasOne('Estudiante', array(
             'local' => 'Estudiante_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}