<?php

/**
 * BaseEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $apellidos
 * @property string $nombres
 * @property string $numero_documento
 * @property string $direccion_1
 * @property string $direccion_2
 * @property string $acudiente
 * @property string $telefono
 * @property string $movil
 * @property string $email
 * @property integer $TipoDocumento_id
 * @property integer $Municipio_id
 * @property integer $Genero_id
 * @property integer $Institucion_id
 * @property Municipio $Municipio
 * @property Genero $Genero
 * @property Institucion $Institucion
 * @property TipoDocumento $TipoDocumento
 * @property Doctrine_Collection $Asistencias
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getApellidos()        Returns the current record's "apellidos" value
 * @method string              getNombres()          Returns the current record's "nombres" value
 * @method string              getNumeroDocumento()  Returns the current record's "numero_documento" value
 * @method string              getDireccion1()       Returns the current record's "direccion_1" value
 * @method string              getDireccion2()       Returns the current record's "direccion_2" value
 * @method string              getAcudiente()        Returns the current record's "acudiente" value
 * @method string              getTelefono()         Returns the current record's "telefono" value
 * @method string              getMovil()            Returns the current record's "movil" value
 * @method string              getEmail()            Returns the current record's "email" value
 * @method integer             getTipoDocumentoId()  Returns the current record's "TipoDocumento_id" value
 * @method integer             getMunicipioId()      Returns the current record's "Municipio_id" value
 * @method integer             getGeneroId()         Returns the current record's "Genero_id" value
 * @method integer             getInstitucionId()    Returns the current record's "Institucion_id" value
 * @method Municipio           getMunicipio()        Returns the current record's "Municipio" value
 * @method Genero              getGenero()           Returns the current record's "Genero" value
 * @method Institucion         getInstitucion()      Returns the current record's "Institucion" value
 * @method TipoDocumento       getTipoDocumento()    Returns the current record's "TipoDocumento" value
 * @method Doctrine_Collection getAsistencias()      Returns the current record's "Asistencias" collection
 * @method Estudiante          setId()               Sets the current record's "id" value
 * @method Estudiante          setApellidos()        Sets the current record's "apellidos" value
 * @method Estudiante          setNombres()          Sets the current record's "nombres" value
 * @method Estudiante          setNumeroDocumento()  Sets the current record's "numero_documento" value
 * @method Estudiante          setDireccion1()       Sets the current record's "direccion_1" value
 * @method Estudiante          setDireccion2()       Sets the current record's "direccion_2" value
 * @method Estudiante          setAcudiente()        Sets the current record's "acudiente" value
 * @method Estudiante          setTelefono()         Sets the current record's "telefono" value
 * @method Estudiante          setMovil()            Sets the current record's "movil" value
 * @method Estudiante          setEmail()            Sets the current record's "email" value
 * @method Estudiante          setTipoDocumentoId()  Sets the current record's "TipoDocumento_id" value
 * @method Estudiante          setMunicipioId()      Sets the current record's "Municipio_id" value
 * @method Estudiante          setGeneroId()         Sets the current record's "Genero_id" value
 * @method Estudiante          setInstitucionId()    Sets the current record's "Institucion_id" value
 * @method Estudiante          setMunicipio()        Sets the current record's "Municipio" value
 * @method Estudiante          setGenero()           Sets the current record's "Genero" value
 * @method Estudiante          setInstitucion()      Sets the current record's "Institucion" value
 * @method Estudiante          setTipoDocumento()    Sets the current record's "TipoDocumento" value
 * @method Estudiante          setAsistencias()      Sets the current record's "Asistencias" collection
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('apellidos', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('nombres', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('numero_documento', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('direccion_1', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('direccion_2', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('acudiente', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('movil', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('TipoDocumento_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Genero_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('Institucion_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_Estudiante_Municipio1', array(
             'fields' => 
             array(
              0 => 'Municipio_id',
             ),
             ));
        $this->index('fk_Estudiante_Genero1', array(
             'fields' => 
             array(
              0 => 'Genero_id',
             ),
             ));
        $this->index('fk_Estudiante_Institucion1', array(
             'fields' => 
             array(
              0 => 'Institucion_id',
             ),
             ));
        $this->index('fk_Estudiante_TipoDocumento1', array(
             'fields' => 
             array(
              0 => 'TipoDocumento_id',
             ),
             ));
        $this->option('charset', 'latin1');
        $this->option('collate', 'latin1_spanish_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Municipio', array(
             'local' => 'Municipio_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('Genero', array(
             'local' => 'Genero_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('Institucion', array(
             'local' => 'Institucion_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('TipoDocumento', array(
             'local' => 'TipoDocumento_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasMany('Asistencia as Asistencias', array(
             'local' => 'id',
             'foreign' => 'Estudiante_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'apellidos',
              1 => 'nombres',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}