<?php

/**
 * BaseTipoInstitucion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Instituciones
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method Doctrine_Collection getInstituciones() Returns the current record's "Instituciones" collection
 * @method TipoInstitucion     setId()            Sets the current record's "id" value
 * @method TipoInstitucion     setNombre()        Sets the current record's "nombre" value
 * @method TipoInstitucion     setDescripcion()   Sets the current record's "descripcion" value
 * @method TipoInstitucion     setInstituciones() Sets the current record's "Instituciones" collection
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoInstitucion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_institucion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('descripcion', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));

        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Institucion as Instituciones', array(
             'local' => 'id',
             'foreign' => 'TipoInstitucion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}