<?php

/**
 * BaseCalendario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $PeriodosAcademicos
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getNombre()             Returns the current record's "nombre" value
 * @method string              getDescripcion()        Returns the current record's "descripcion" value
 * @method Doctrine_Collection getPeriodosAcademicos() Returns the current record's "PeriodosAcademicos" collection
 * @method Calendario          setId()                 Sets the current record's "id" value
 * @method Calendario          setNombre()             Sets the current record's "nombre" value
 * @method Calendario          setDescripcion()        Sets the current record's "descripcion" value
 * @method Calendario          setPeriodosAcademicos() Sets the current record's "PeriodosAcademicos" collection
 * 
 * @package    siglo21
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalendario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('calendario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'latin1_spanish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PeriodoAcademico as PeriodosAcademicos', array(
             'local' => 'id',
             'foreign' => 'Calendario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'descripcion',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}