<?php

/**
 * CursoProgramadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CursoProgramadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CursoProgramadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CursoProgramado');
    }
}