<?php

/**
* PeriodoAcademico
* 
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    siglo21
* @subpackage model
* @author     Your name here
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class PeriodoAcademico extends BasePeriodoAcademico
{
	public function __toString() {
	    return $this->getCodigo();
	}
	
	// public function makeCodigo() {
	// 	if ($this->isNew()){
	// 		$year = $this->getInicio() ? date('Y', strtotime($this->getInicio())) : date('Y', time());
	// 		// $year = date('Y', time());
	// 		$calendario = $this->getCalendario()->getNombre();
	// 		$codigo = $year . $calendario;
	// 		$this->setCodigo($codigo);
	// 	}
	// }
	
	// public function save(Doctrine_Connection $conn = null){
	// 	$this->makeCodigo();
	// 	return parent::save($conn);
	// }
}
