<?php

/**
 * ProgramacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Programacion');
    }
}