generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CursoProgramado
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              CursoProgramado
    plural:                CursosProgramados
    route_prefix:          curso_programado
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Curso_id:
          label:  Curso
        descripcion:
          label:  Descripción
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
