---
detect_relations: true
options:
  collate: latin1_spanish_ci
  charset: latin1
  type: InnoDB

Municipio:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    codigo:
      type: integer(4)
      unique: true
      notnull: true
    nombre:
      type: string(60)
      notnull: true

Genero:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(45)
      unique: true
      notnull: true
    abreviacion:
      type: string(1)
      notnull: true

Perfil:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(60)
      unique: true
      notnull: true
    descripcion:
      type: string(255)
      notnull: true

TipoInstitucion:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(45)
      notnull: true
    descripcion:
      type: string(128)
      notnull: true

Institucion:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre_corto]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(255)
      unique: true
      notnull: true
    nombre_corto:
      type: string(60)
      notnull: true
    direccion_1:
      type: string(80)
      notnull: true
    direccion_2:
      type: string(80)
    telefono_1:
      type: string(20)
      notnull: true
    telefono_2:
      type: string(45)
    fax:
      type: string(20)
    email:
      type: string(128)
      notnull: true
    web:
      type: string(128)
    TipoInstitucion_id:
      type: integer(4)
      notnull: true
    Municipio_id:
      type: integer(4)
      notnull: true
  relations:
    TipoInstitucion:
      class: TipoInstitucion
      local: TipoInstitucion_id
      foreign: id
      foreignAlias: Instituciones
      onDelete: cascade
      onUpdate: cascade
    Municipio:
      class: Municipio
      local: Municipio_id
      foreign: id
      foreignAlias: Instituciones
      onDelete: cascade
      onUpdate: cascade
  indexes:
    fk_Institucion_TipoInstitucion1:
      fields: [TipoInstitucion_id]
    fk_Institucion_Municipio1:
      fields: [Municipio_id]

Estudiante:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [apellidos, nombres]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    apellidos:
      type: string(128)
      notnull: true
    nombres:
      type: string(128)
      notnull: true
    numero_documento:
      type: string(45)
      notnull: true
    direccion_1:
      type: string(128)
      notnull: true
    direccion_2:
      type: string(128)
    acudiente:
      type: string(128)
      notnull: true
    telefono:
      type: string(20)
      notnull: true
    movil:
      type: string(20)
    email:
      type: string(128)
      notnull: true
    Municipio_id:
      type: integer(4)
      notnull: true
    Genero_id:
      type: integer(4)
      notnull: true
    Institucion_id:
      type: integer(4)
      notnull: true
    TipoDocumento_id:
      type: integer(4)
      notnull: true
  relations:
    Municipio:
      class: Municipio
      local: Municipio_id
      foreign: id
      foreignAlias: Estudiantes
      onDelete: cascade
      onUpdate: cascade
    Genero:
      class: Genero
      local: Genero_id
      foreign: id
      foreignAlias: Estudiantes
      onDelete: cascade
      onUpdate: cascade
    Institucion:
      class: Institucion
      local: Institucion_id
      foreign: id
      foreignAlias: Estudiantes
      onDelete: cascade
      onUpdate: cascade
    TipoDocumento:
      class: TipoDocumento
      local: TipoDocumento_id
      foreign: id
      foreignAlias: Estudiantes
      onDelete: cascade
      onUpdate: cascade
  indexes:
    fk_Estudiante_Municipio1:
      fields: [Municipio_id]
    fk_Estudiante_Genero1:
      fields: [Genero_id]
    fk_Estudiante_Institucion1:
      fields: [Institucion_id]
    fk_Estudiante_TipoDocumento1:
      fields: [TipoDocumento_id]

Usuario:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [apellidos, nombres]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    apellidos:
      type: string(128)
      notnull: true
    nombres:
      type: string(128)
      notnull: true
    telefono:
      type: string(20)
      notnull: true
    movil:
      type: string(20)
    email:
      type: string(128)
      notnull: true
    username:
      type: string(20)
      notnull: true
    password:
      type: string(20)
      notnull: true
    Perfil_id:
      type: integer(4)
      notnull: true
  relations:
    Perfil:
      class: Perfil
      local: Perfil_id
      foreign: id
      foreignAlias: Usuarios
      onDelete: cascade
      onUpdate: cascade
  indexes:
    fk_Usuario_Perfil1:
      fields: [Perfil_id]

Servicio:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(128)
      notnull: true
    descripcion:
      type: string(255)
      notnull: true
    valor:
      type: decimal(8,2)

      notnull: true

Curso:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre_corto]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    codigo:
      type: string(45)
      notnull: true
    nombre:
      type: string(128)
      notnull: true
    nombre_corto:
      type: string(60)
      notnull: true
    descripcion:
      type: string(255)
    Servicio_id:
      type: integer(4)
      notnull: true
  relations:
    Servicio:
      class: Servicio
      local: Servicio_id
      foreign: id
      foreignAlias: Cursos
      onDelete: cascade
      onUpdate: cascade
  indexes:
    fk_Curso_Servicio1:
      fields: [Servicio_id]

CursoProgramado:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    grupo:
      type: integer(4)
      notnull: true
    descripcion:
      type: string(128)
      notnull: true
    grado:
      type: integer(4)
      notnull: true
    fecha_inicio:
      type: date
      notnull: true
    fecha_finalizacion:
      type: date
      notnull: true
    Curso_id:
      type: integer(4)
      notnull: true
    Institucion_id:
      type: integer(4)
      notnull: true
    PeriodoAcademico_id:
      type: integer(4)
      notnull: true
  relations:
    Curso:
      class: Curso
      local: Curso_id
      foreign: id
      foreignAlias: CursosProgramados
      onDelete: cascade
      onUpdate: cascade
    Institucion:
      class: Institucion
      local: Institucion_id
      foreign: id
      foreignAlias: CursosProgramados
      onDelete: cascade
      onUpdate: cascade
    PeriodoAcademico:
      class: PeriodoAcademico
      local: PeriodoAcademico_id
      foreign: id
      foreignAlias: CursosProgramados
      onDelete: cascade
      onUpdate: cascade
  indexes:
    fk_CursoProgramado_Curso1:
      fields: [Curso_id]
    fk_CursoProgramado_Institucion1:
      fields: [Institucion_id]
    fk_CursoProgramado_PeriodoAcademico1:
      fields: [PeriodoAcademico_id]

Asistencia:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    fecha:
      type: timestamp
      notnull: true
    asistio:
      type: boolean
      notnull: true
    Estudiante_id:
      type: integer(4)
      notnull: true
    CursoProgramado_id:
      type: integer(4)
      notnull: true
    CursoProgramado_Curso_id:
      type: integer(4)
      notnull: true
    CursoProgramado_Institucion_id:
      type: integer(4)
      notnull: true
  relations:
    Estudiante:
      class: Estudiante
      local: Estudiante_id
      foreign: id
      foreignAlias: Asistencias
      onDelete: cascade
      onUpdate: cascade
    CursoProgramadoCurso:
      class: CursoProgramado
      local: CursoProgramado_Curso_id
      foreign: Curso_id
      foreignAlias: Asistencias
      onDelete: cascade
      onUpdate: cascade
  indexes:
    fk_Asistencia_Estudiante1:
      fields: [Estudiante_id]
    fk_Asistencia_CursoProgramado1:
      fields: [CursoProgramado_id, CursoProgramado_Curso_id, CursoProgramado_Institucion_id]

TipoDocumento:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [nombre]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(6)
    descripcion:
      type: string(60)

PeriodoAcademico:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    codigo:
      type: string(15)
      unique: true
      notnull: true
    inicio:
      type: date
    fin:
      type: date
    activo:
      type: boolean
    comentarios:
      type: string(255)
    Calendario_id:
      type: integer(4)
      notnull: true
  relations:
    Calendario:
      class: Calendario
      local: Calendario_id
      foreign: id
      foreignAlias: PeriodosAcademicos
      onDelete: cascade
      onUpdate: cascade
  indexes:
    fk_PeriodoAcademico_Calendario1:
      fields: [Calendario_id]

Calendario:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:    [descripcion]
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(10)
      notnull: true
    descripcion:
      type: string(255)
      notnull: true

Matricula:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    fecha:
      type: date
    CursoProgramado_Curso_id:
      type: integer(4)
      notnull: true
    CursoProgramado_Institucion_id:
      type: integer(4)
      notnull: true
    CursoProgramado_PeriodoAcademico_id:
      type: integer(4)
      notnull: true
    Estudiante_id:
      type: integer(4)
      notnull: true
  relations:
    CursoProgramadoCurso:
      class: CursoProgramado
      local: CursoProgramado_Curso_id
      foreign: Curso_id
      foreignAlias: Matriculas
    Estudiante:
      class: Estudiante
      local: Estudiante_id
      foreign: id
      foreignAlias: Matriculas
  indexes:
    fk_Matricula_CursoProgramado1:
      fields: [CursoProgramado_Curso_id, CursoProgramado_Institucion_id, CursoProgramado_PeriodoAcademico_id]
    fk_Matricula_Estudiante1:
      fields: [Estudiante_id]

